[package]
name = "backend"
<<<<<<< HEAD
version = "0.1.0"
authors = ["Dawid J. Kubis <dawidk.kubis3@gmail.com>", "Lukáš Hozda <luk.hozda@gmail.com>", "Lukáš Veškrna <lukas.veskrna@gmail.com>"]
=======
version = "0.12.0"
authors = ["Dawid J. Kubis <dawidk.kubis3@gmail.com>", "Lukáš Hozda <luk.hozda@gmail.com>"]
>>>>>>> 353f4496e8870e577ca2a1c1345d2f582e5c8e87
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
dotenv = "0.15.0"
diesel = "1.4.3"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.42"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["diesel_sqlite_pool", "json"]
